### ISSUE TITLE
Affect disliked items in search results

### ISSUE THREAD

**Issue by tDeranek117** [spencerking/CSE40746-Final-Project#35]

**Comment by Gofake1** [comment]
I think we should gray them out instead of completely hide it.
Or put the result closer to the bottom.

**Comment by tDeranek117** [comment]
Hmm... well, it could be more complicated to move them to the bottom. And the whole point of it is to filter out the bad, unwanted items. Perhaps we remove them from this list and make them visible on their own page so that people can remove the "dislike" if they wish.
